export const ADD_USER_INFO="ADD_USER_INFO"
export const ADD_COND_INFO="ADD_COND_INFO"
export const ADD_SHIFT_INFO="ADD_SHIFT_INFO"
export const EDIT_ARRAY="EDIT_ARRAY"
export const DELETE_ITEM = "DELETE_ITEM";